// <auto-generated />
using EfCoreRemoveMigrationIssueSample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfCoreRemoveMigrationIssueSample.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    partial class SampleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EfCoreRemoveMigrationIssueSample.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasDiscriminator<string>("Type");
                });

            modelBuilder.Entity("EfCoreRemoveMigrationIssueSample.Customer", b =>
                {
                    b.HasBaseType("EfCoreRemoveMigrationIssueSample.Person");

                    b.Property<decimal>("AmountSpent");

                    b.ToTable("Customer");

                    b.HasDiscriminator().HasValue("C");
                });

            modelBuilder.Entity("EfCoreRemoveMigrationIssueSample.Employee", b =>
                {
                    b.HasBaseType("EfCoreRemoveMigrationIssueSample.Person");

                    b.Property<decimal>("Salary");

                    b.ToTable("Employee");

                    b.HasDiscriminator().HasValue("E");
                });
#pragma warning restore 612, 618
        }
    }
}
